POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "username": "maria",
    "password": "guess"
}

###
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlhIiwic3ViIjoyLCJyb2xlcyI6WyJBZG1pbiJdLCJpYXQiOjE2NzAwNDU2NzYsImV4cCI6MTY3MDA0NTczNn0.7DzX2olHm0MqpG94iZIX1b6XZNA82IuzeKwE8OIPfh0
###
GET http://localhost:3000/only_admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hcmlhIiwic3ViIjoyLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE2NzAwNDU3NTYsImV4cCI6MTY3MDA0NTgxNn0.Q-mvwrIAM1-Be4xHGulrSf-0VWpvY4LUNRp1xHQn2iE